import React, { useEffect, useState, useContext } from 'react';
import { AuthContext } from '../../context/AuthContext';
import {
    FaFileDownload, FaSolarPanel, FaFileInvoiceDollar,
    FaTools, FaBoxOpen, FaUsers, FaFilter, FaSync, FaCheckCircle,
    FaBolt, FaClock, FaChartBar, FaExclamationTriangle
} from 'react-icons/fa';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { toast } from 'react-toastify';

function Reports() {
    const { user } = useContext(AuthContext);
    const [energyData, setEnergyData] = useState([]);
    const [userData, setUserData] = useState([]);
    const [inventoryData, setInventoryData] = useState([]);

    // Filter states
    const [dateRange, setDateRange] = useState('7');
    const [reportType, setReportType] = useState('all');
    const [format, setFormat] = useState('pdf');
    const [customDateFrom, setCustomDateFrom] = useState('');
    const [customDateTo, setCustomDateTo] = useState('');
    const [generating, setGenerating] = useState(false);

    const isAdmin = user?.role === 'ADMIN'; // ✅ single source of truth

    useEffect(() => {
        fetchData();
    }, [user, dateRange]);

    const fetchData = () => {
        const daysParam = dateRange === 'custom' ? 30 : dateRange;

        fetch(`/api/stats/chart?role=ADMIN&days=${daysParam}`)
            .then(res => res.json())
            .then(data => setEnergyData(data))
            .catch(err => console.error("Energy fetch failed", err));

        // ✅ Only fetch admin data if user is ADMIN
        if (isAdmin) {
            fetch(`/api/users`)
                .then(res => res.json())
                .then(data => setUserData(data))
                .catch(err => console.error("User fetch failed", err));

            fetch(`/api/inventory`)
                .then(res => res.json())
                .then(data => setInventoryData(Array.isArray(data) ? data : []))
                .catch(err => console.error("Inventory fetch failed", err));
        }
    };

    const handleGenerateReport = async () => {
        setGenerating(true);
        try {
            if (reportType === 'all' || reportType === 'users') {
                if (isAdmin) await downloadUserReport();
            }
            if (reportType === 'all' || reportType === 'energy') {
                await downloadEnergyReport();
            }
            // ✅ Inventory report — ADMIN only
            if ((reportType === 'all' || reportType === 'inventory') && isAdmin) {
                await downloadInventoryReport();
            }
            toast.success(`${reportType === 'all' ? 'All reports' : reportType.charAt(0).toUpperCase() + reportType.slice(1) + ' report'} generated successfully!`);
        } catch (error) {
            toast.error("Failed to generate report. Please try again.");
        } finally {
            setGenerating(false);
        }
    };

    const handleResetFilters = () => {
        setDateRange('7');
        setReportType('all');
        setFormat('pdf');
        setCustomDateFrom('');
        setCustomDateTo('');
        toast.info("Filters reset to default");
    };

    // --- REPORT 1: USER DIRECTORY (ADMIN only) ---
    const downloadUserReport = () => {
        return new Promise((resolve, reject) => {
            try {
                const doc = new jsPDF();
                doc.setFontSize(18);
                doc.setTextColor(40, 167, 69);
                doc.text("SGEMS - System Users Directory", 14, 20);
                doc.setFontSize(10);
                doc.setTextColor(100);
                doc.text(`Generated By: ${user.fullName} (User Admin)`, 14, 28);
                doc.text(`Date: ${new Date().toLocaleDateString()}`, 14, 33);
                doc.text(`Total Active Users: ${userData.length}`, 14, 38);
                doc.text(`Date Range: Last ${dateRange} days`, 14, 43);
                autoTable(doc, {
                    head: [["ID", "Full Name", "Email", "Role", "Status"]],
                    body: userData.map(u => [u.id, u.fullName, u.email, u.role, "Active"]),
                    startY: 50,
                    theme: 'grid',
                    headStyles: { fillColor: [40, 167, 69] }
                });
                doc.save(`SGEMS_User_Report_${new Date().toISOString().split('T')[0]}.pdf`);
                resolve();
            } catch (e) { reject(e); }
        });
    };

    // --- REPORT 2: ENERGY GENERATION (all users) ---
    const downloadEnergyReport = () => {
        return new Promise((resolve, reject) => {
            try {
                const doc = new jsPDF();
                doc.setFontSize(18);
                doc.setTextColor(255, 193, 7);
                doc.text("SGEMS - Site Energy Generation", 14, 20);
                doc.setFontSize(10);
                doc.setTextColor(100);
                doc.text(`Generated By: ${user.fullName} (Site Admin)`, 14, 28);
                doc.text(`Date: ${new Date().toLocaleDateString()}`, 14, 33);
                doc.text(`Date Range: Last ${dateRange} days`, 14, 38);
                doc.text(`Total Records: ${energyData.length}`, 14, 43);
                const totalGenerated = energyData.reduce((sum, row) => sum + row.generated, 0);
                const totalConsumed = energyData.reduce((sum, row) => sum + row.consumed, 0);
                const totalSavings = totalGenerated * 0.15;
                doc.text(`Total Generated: ${totalGenerated.toFixed(2)} kWh`, 14, 48);
                doc.text(`Total Consumed: ${totalConsumed.toFixed(2)} kWh`, 14, 53);
                doc.text(`Total Savings: $${totalSavings.toFixed(2)}`, 14, 58);
                autoTable(doc, {
                    head: [["Day", "Generated (kWh)", "Consumed (kWh)", "Savings ($)"]],
                    body: energyData.map(row => [
                        row.day,
                        row.generated.toFixed(2),
                        row.consumed.toFixed(2),
                        `$${(row.generated * 0.15).toFixed(2)}`
                    ]),
                    startY: 65,
                    headStyles: { fillColor: [255, 193, 7], textColor: [0, 0, 0] }
                });
                doc.save(`SGEMS_Energy_Report_${new Date().toISOString().split('T')[0]}.pdf`);
                resolve();
            } catch (e) { reject(e); }
        });
    };

    // --- REPORT 3: INVENTORY ASSETS (ADMIN only) ---
    const downloadInventoryReport = () => {
        return new Promise((resolve, reject) => {
            try {
                const doc = new jsPDF();
                doc.setFontSize(18);
                doc.setTextColor(45, 143, 165);
                doc.text("SGEMS - Inventory Assets Report", 14, 20);
                doc.setFontSize(10);
                doc.setTextColor(100);
                doc.text(`Generated By: ${user.fullName}`, 14, 28);
                doc.text(`Date: ${new Date().toLocaleDateString()}`, 14, 33);
                doc.text(`Total Assets: ${inventoryData.length}`, 14, 38);
                const totalQty = inventoryData.reduce((sum, item) => sum + (item.quantity || 0), 0);
                const available = inventoryData.filter(i => i.status === 'Available').length;
                const inUse = inventoryData.filter(i => i.status === 'In Use').length;
                doc.text(`Total Quantity: ${totalQty}`, 14, 43);
                doc.text(`Available: ${available}   In Use: ${inUse}   Other: ${inventoryData.length - available - inUse}`, 14, 48);
                autoTable(doc, {
                    head: [["ID", "Asset Name", "Category", "Location", "Qty", "Status"]],
                    body: inventoryData.map(item => [
                        item.id, item.name, item.category,
                        item.location || '—', item.quantity, item.status
                    ]),
                    startY: 56,
                    theme: 'grid',
                    headStyles: { fillColor: [45, 143, 165] },
                    bodyStyles: { fontSize: 9 },
                    alternateRowStyles: { fillColor: [240, 249, 252] }
                });
                doc.save(`SGEMS_Inventory_Report_${new Date().toISOString().split('T')[0]}.pdf`);
                resolve();
            } catch (e) { reject(e); }
        });
    };

    const downloadAlertReport = async () => {
        try {
            const start = dateRange === 'custom' ? customDateFrom : getDefaultStartDate();
            const end   = dateRange === 'custom' ? customDateTo   : new Date().toISOString().split('T')[0];
            const res = await fetch(`/api/alerts/reports/history?startDate=${start}&endDate=${end}`);
            const data = await res.json();

            const doc = new jsPDF();
            doc.setFontSize(18);
            doc.setTextColor(239, 68, 68);
            doc.text("SGEMS - Alert History Report", 14, 20);
            doc.setFontSize(10);
            doc.text(`Generated By: ${user.fullName} (Alert Admin)`, 14, 28);
            doc.text(`Period: ${data.dateRange}`, 14, 33);
            doc.text(`Total Alerts: ${data.total}`, 14, 38);

            autoTable(doc, {
                head: [["System ID", "Issue", "Severity", "Status", "Battery %", "Deleted At"]],
                body: data.alerts.map(alert => [
                    alert.systemId, alert.issue, alert.severity,
                    alert.status, alert.battery,
                    new Date(alert.deletedAt).toLocaleString()
                ]),
                startY: 45,
                headStyles: { fillColor: [239, 68, 68] }
            });
            doc.save(`SGEMS_Alert_Report_${new Date().toISOString().split('T')[0]}.pdf`);
            toast.success("Alert report generated");
        } catch (err) {
            toast.error("Failed to generate alert report");
        }
    };

    const getDefaultStartDate = () => {
        const days = parseInt(dateRange);
        const d = new Date();
        d.setDate(d.getDate() - days);
        return d.toISOString().split('T')[0];
    };
    const showPendingAlert = (name) => {
        toast.info(`🚧 Waiting for ${name} to implement their API endpoint!`);
    };

    const dateRangeLabel = dateRange === 'custom'
        ? `${customDateFrom} → ${customDateTo}`
        : `Last ${dateRange} days`;

    const reportTypeLabel = reportType === 'all'
        ? 'All Reports'
        : reportType.charAt(0).toUpperCase() + reportType.slice(1);

    return (
        <>
            <style>{`
                @import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700&family=DM+Sans:wght@300;400;500&display=swap');
                :root { --forest:#1a3a2a; --moss:#2d5a3d; --sage:#5a8a6a; --mint:#a8d5b5; --cream:#f5f0e8; --warm-white:#fdfaf5; --gold:#c9a84c; }
                .gg-reports { font-family:'DM Sans',sans-serif; padding:32px 36px; min-height:100vh; background:var(--warm-white); position:relative; }
                .gg-rp-blob { position:fixed; border-radius:50%; filter:blur(90px); pointer-events:none; z-index:0; }
                .gg-rp-blob-1 { width:450px; height:450px; background:radial-gradient(circle,rgba(168,213,181,0.16) 0%,transparent 70%); top:-100px; right:0; }
                .gg-rp-blob-2 { width:300px; height:300px; background:radial-gradient(circle,rgba(201,168,76,0.1) 0%,transparent 70%); bottom:100px; left:20%; }
                .gg-rp-content { position:relative; z-index:1; }
                .gg-rp-eyebrow { font-size:10.5px; font-weight:500; letter-spacing:2.5px; text-transform:uppercase; color:var(--sage); margin-bottom:6px; display:flex; align-items:center; gap:8px; }
                .gg-rp-eyebrow::before { content:''; display:inline-block; width:18px; height:2px; background:var(--gold); border-radius:2px; }
                .gg-rp-h1 { font-family:'Playfair Display',serif; font-size:clamp(26px,3vw,36px); font-weight:700; color:var(--forest); letter-spacing:-0.5px; margin:0 0 6px; line-height:1.15; }
                .gg-rp-sub { font-size:14px; font-weight:300; color:#6a8a78; margin:0 0 28px; }
                .gg-rp-card { background:rgba(255,255,255,0.88); border:1px solid rgba(168,213,181,0.3); border-radius:18px; overflow:hidden; box-shadow:0 4px 20px rgba(26,58,42,0.08); margin-bottom:24px; }
                .gg-rp-card-header { padding:14px 22px; display:flex; align-items:center; gap:8px; font-size:13.5px; font-weight:500; color:var(--forest); background:rgba(245,240,232,0.5); border-bottom:1px solid rgba(168,213,181,0.2); }
                .gg-rp-card-header svg { color:var(--moss); }
                .gg-rp-card-body { padding:22px; }
                .gg-rp-filter-grid { display:grid; grid-template-columns:repeat(3,1fr); gap:16px; margin-bottom:16px; }
                @media (max-width:900px) { .gg-rp-filter-grid { grid-template-columns:1fr 1fr; } }
                @media (max-width:600px) { .gg-rp-filter-grid { grid-template-columns:1fr; } }
                .gg-rp-custom-dates { display:grid; grid-template-columns:1fr 1fr; gap:16px; margin-bottom:16px; }
                .gg-rp-label { display:block; font-size:10.5px; font-weight:500; letter-spacing:1.5px; text-transform:uppercase; color:var(--moss); margin-bottom:7px; }
                .gg-rp-select, .gg-rp-date-input { width:100%; padding:10px 14px; font-family:'DM Sans',sans-serif; font-size:13.5px; color:var(--forest); background:rgba(245,240,232,0.6); border:1.5px solid rgba(90,138,106,0.22); border-radius:10px; outline:none; transition:border-color 0.2s,box-shadow 0.2s; box-sizing:border-box; cursor:pointer; }
                .gg-rp-select { -webkit-appearance:none; appearance:none; background-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='12' viewBox='0 0 24 24' fill='none' stroke='%235a8a6a' stroke-width='2'%3E%3Cpolyline points='6 9 12 15 18 9'%3E%3C/polyline%3E%3C/svg%3E"); background-repeat:no-repeat; background-position:right 12px center; padding-right:36px; background-color:rgba(245,240,232,0.6); }
                .gg-rp-select:focus, .gg-rp-date-input:focus { border-color:var(--moss); background-color:#fff; box-shadow:0 0 0 3px rgba(90,138,106,0.1); }
                .gg-rp-actions { display:flex; gap:10px; align-items:center; flex-wrap:wrap; }
                .gg-rp-btn-generate { display:inline-flex; align-items:center; gap:8px; padding:11px 22px; background:linear-gradient(135deg,var(--forest),var(--moss)); color:var(--cream); border:none; border-radius:10px; font-family:'DM Sans',sans-serif; font-size:13.5px; font-weight:500; cursor:pointer; transition:transform 0.2s,box-shadow 0.2s; box-shadow:0 4px 14px rgba(26,58,42,0.25); }
                .gg-rp-btn-generate:hover:not(:disabled) { transform:translateY(-2px); box-shadow:0 7px 20px rgba(26,58,42,0.3); }
                .gg-rp-btn-generate:disabled { opacity:0.65; cursor:not-allowed; }
                .gg-rp-btn-reset { display:inline-flex; align-items:center; gap:8px; padding:11px 18px; background:rgba(168,213,181,0.12); border:1.5px solid rgba(168,213,181,0.3); border-radius:10px; font-family:'DM Sans',sans-serif; font-size:13.5px; font-weight:500; color:var(--sage); cursor:pointer; transition:all 0.2s; }
                .gg-rp-btn-reset:hover { background:rgba(168,213,181,0.22); color:var(--forest); }
                .gg-rp-summary { display:flex; align-items:center; gap:8px; margin-top:16px; padding:10px 14px; background:rgba(45,90,61,0.06); border:1px solid rgba(45,90,61,0.12); border-radius:10px; font-size:12.5px; color:var(--moss); }
                .gg-rp-summary svg { color:var(--gold); flex-shrink:0; }
                .gg-rp-pill { display:inline-block; padding:2px 9px; background:rgba(45,90,61,0.1); border-radius:20px; font-weight:500; font-size:12px; }
                .gg-rp-spin { width:14px; height:14px; border:2px solid rgba(255,255,255,0.3); border-top-color:white; border-radius:50%; animation:rpSpin 0.7s linear infinite; display:inline-block; }
                @keyframes rpSpin { to { transform:rotate(360deg); } }
                .gg-rp-section-label { display:flex; align-items:center; gap:10px; font-size:11px; font-weight:500; letter-spacing:2px; text-transform:uppercase; color:var(--sage); margin:28px 0 16px; }
                .gg-rp-section-label::after { content:''; flex:1; height:1px; background:rgba(168,213,181,0.3); }
                .gg-rp-grid-2 { display:grid; grid-template-columns:repeat(2,1fr); gap:16px; }
                .gg-rp-grid-3 { display:grid; grid-template-columns:repeat(3,1fr); gap:16px; }
                @media (max-width:900px) { .gg-rp-grid-2 { grid-template-columns:1fr; } .gg-rp-grid-3 { grid-template-columns:1fr 1fr; } }
                @media (max-width:600px) { .gg-rp-grid-3 { grid-template-columns:1fr; } }
                .gg-rp-report-card { background:rgba(255,255,255,0.88); border:1px solid rgba(168,213,181,0.28); border-radius:16px; padding:22px; box-shadow:0 4px 16px rgba(26,58,42,0.07); transition:transform 0.22s,box-shadow 0.22s; position:relative; overflow:hidden; animation:rpCardIn 0.45s cubic-bezier(.22,1,.36,1) both; }
                .gg-rp-report-card::before { content:''; position:absolute; top:0; left:0; right:0; height:3px; border-radius:16px 16px 0 0; }
                .gg-rp-report-card:hover { transform:translateY(-3px); box-shadow:0 10px 28px rgba(26,58,42,0.12); }
                .gg-rp-report-card.pending { opacity:0.72; }
                @keyframes rpCardIn { from{opacity:0;transform:translateY(14px)} to{opacity:1;transform:translateY(0)} }
                .gg-rp-report-card-top { display:flex; align-items:flex-start; justify-content:space-between; margin-bottom:12px; }
                .gg-rp-report-icon { width:40px; height:40px; border-radius:11px; display:flex; align-items:center; justify-content:center; font-size:16px; flex-shrink:0; }
                .gg-rp-badge { font-size:10px; font-weight:600; letter-spacing:0.8px; text-transform:uppercase; padding:3px 9px; border-radius:6px; }
                .gg-rp-report-title { font-size:15px; font-weight:500; color:var(--forest); margin-bottom:6px; }
                .gg-rp-report-desc { font-size:12.5px; color:#7a9688; font-weight:300; line-height:1.55; margin-bottom:16px; }
                .gg-rp-owner { font-size:11px; color:#9ab5a5; margin-bottom:14px; }
                .gg-rp-dl-btn { width:100%; display:flex; align-items:center; justify-content:center; gap:7px; padding:10px; border-radius:10px; font-family:'DM Sans',sans-serif; font-size:13px; font-weight:500; cursor:pointer; border:none; transition:all 0.2s; }
                .gg-rp-dl-btn:hover { opacity:0.88; transform:translateY(-1px); }
                .gg-rp-live-badge { display:inline-flex; align-items:center; gap:5px; font-size:9.5px; font-weight:600; letter-spacing:0.8px; text-transform:uppercase; padding:3px 8px; border-radius:6px; background:rgba(45,143,165,0.1); color:#2d8fa5; border:1px solid rgba(45,143,165,0.2); }
                .gg-rp-live-dot { width:6px; height:6px; border-radius:50%; background:#2d8fa5; animation:livePulse 2s ease-in-out infinite; }
                @keyframes livePulse { 0%,100%{box-shadow:0 0 0 0 rgba(45,143,165,0.4)} 50%{box-shadow:0 0 0 3px rgba(45,143,165,0.1)} }
            `}</style>

            <div className="gg-rp-blob gg-rp-blob-1" />
            <div className="gg-rp-blob gg-rp-blob-2" />

            <div className="gg-rp-content">
                <div className="gg-rp-eyebrow"><FaChartBar /> Analytics</div>
                <h1 className="gg-rp-h1">System Reports Hub</h1>
                <p className="gg-rp-sub">Generate legal and operational reports for all system modules.</p>

                {/* ── FILTER CARD ───────────────────────────────────────── */}
                <div className="gg-rp-card">
                    <div className="gg-rp-card-header"><FaFilter /> Report Filters & Customization</div>
                    <div className="gg-rp-card-body">
                        <div className="gg-rp-filter-grid">
                            <div>
                                <label className="gg-rp-label">Date Range</label>
                                <select className="gg-rp-select" value={dateRange} onChange={e => setDateRange(e.target.value)}>
                                    <option value="7">Last 7 Days</option>
                                    <option value="14">Last 14 Days</option>
                                    <option value="30">Last 30 Days</option>
                                    <option value="90">Last 90 Days</option>
                                    <option value="custom">Custom Range</option>
                                </select>
                            </div>
                            <div>
                                <label className="gg-rp-label">Report Type</label>
                                <select className="gg-rp-select" value={reportType} onChange={e => setReportType(e.target.value)}>
                                    <option value="all">All Reports</option>
                                    <option value="energy">Energy Generation</option>
                                    {/* ✅ Admin-only options */}
                                    {isAdmin && <option value="users">User Directory</option>}
                                    {isAdmin && <option value="inventory">Inventory Assets</option>}
                                </select>
                            </div>
                            <div>
                                <label className="gg-rp-label">Export Format</label>
                                <select className="gg-rp-select" value={format} onChange={e => setFormat(e.target.value)}>
                                    <option value="pdf">PDF Document</option>
                                    <option value="excel">Excel Spreadsheet (Coming Soon)</option>
                                    <option value="csv">CSV File (Coming Soon)</option>
                                </select>
                            </div>
                        </div>

                        {dateRange === 'custom' && (
                            <div className="gg-rp-custom-dates">
                                <div>
                                    <label className="gg-rp-label">From Date</label>
                                    <input type="date" className="gg-rp-date-input" value={customDateFrom} onChange={e => setCustomDateFrom(e.target.value)} />
                                </div>
                                <div>
                                    <label className="gg-rp-label">To Date</label>
                                    <input type="date" className="gg-rp-date-input" value={customDateTo} onChange={e => setCustomDateTo(e.target.value)} max={new Date().toISOString().split('T')[0]} />
                                </div>
                            </div>
                        )}

                        <div className="gg-rp-actions">
                            <button className="gg-rp-btn-generate" onClick={handleGenerateReport} disabled={generating}>
                                {generating ? <><span className="gg-rp-spin" /> Generating…</> : <><FaFileDownload /> Generate Report</>}
                            </button>
                            <button className="gg-rp-btn-reset" onClick={handleResetFilters}>
                                <FaSync /> Reset Filters
                            </button>
                        </div>

                        <div className="gg-rp-summary">
                            <FaCheckCircle />
                            <span>Current selection:</span>
                            <span className="gg-rp-pill">{reportTypeLabel}</span>
                            <span>·</span>
                            <span className="gg-rp-pill"><FaClock style={{ marginRight: 4, fontSize: 10 }} />{dateRangeLabel}</span>
                            <span>·</span>
                            <span className="gg-rp-pill">{format.toUpperCase()}</span>
                        </div>
                    </div>
                </div>

                {/* ── YOUR ADMINISTRATIVE REPORTS ──────────────────────── */}
                <div className="gg-rp-section-label">Your Administrative Reports</div>
                <div className={isAdmin ? 'gg-rp-grid-2' : ''}>
                    {/* User Directory — ADMIN only */}
                    {isAdmin && (
                        <div className="gg-rp-report-card" style={{ animationDelay: '0.05s' }}>
                            <style>{`.gg-rp-report-card:nth-child(1)::before { background: #2d5a3d; }`}</style>
                            <div className="gg-rp-report-card-top">
                                <div className="gg-rp-report-icon" style={{ background: 'rgba(45,90,61,0.1)', color: '#2d5a3d', border: '1px solid rgba(45,90,61,0.2)' }}><FaUsers /></div>
                                <span className="gg-rp-badge" style={{ background: 'rgba(45,90,61,0.1)', color: '#2d5a3d' }}>User Admin</span>
                            </div>
                            <div className="gg-rp-report-title">User Directory</div>
                            <div className="gg-rp-report-desc">Exports a list of all registered users, their roles, and account status. Required for security auditing.</div>
                            <button className="gg-rp-dl-btn" onClick={downloadUserReport}
                                    style={{ background: 'linear-gradient(135deg, #1a3a2a, #2d5a3d)', color: '#f5f0e8', boxShadow: '0 4px 14px rgba(26,58,42,0.25)' }}>
                                <FaFileDownload /> Download User Report
                            </button>
                        </div>
                    )}

                    {/* Site Generation — all users */}
                    <div className="gg-rp-report-card" style={{ animationDelay: '0.1s' }}>
                        <style>{`.gg-rp-report-card:nth-child(2)::before { background: #c9a84c; }`}</style>
                        <div className="gg-rp-report-card-top">
                            <div className="gg-rp-report-icon" style={{ background: 'rgba(201,168,76,0.12)', color: '#c9a84c', border: '1px solid rgba(201,168,76,0.25)' }}><FaSolarPanel /></div>
                            <span className="gg-rp-badge" style={{ background: 'rgba(201,168,76,0.12)', color: '#8a6a1a' }}>Site Admin</span>
                        </div>
                        <div className="gg-rp-report-title">Site Generation</div>
                        <div className="gg-rp-report-desc">Exports daily energy production, consumption, and savings analysis from Solarman API.</div>
                        <button className="gg-rp-dl-btn" onClick={downloadEnergyReport}
                                style={{ background: 'linear-gradient(135deg, #8a6a1a, #c9a84c)', color: '#fff', boxShadow: '0 4px 14px rgba(201,168,76,0.3)' }}>
                            <FaFileDownload /> Download Energy Report
                        </button>
                    </div>
                </div>

                {/* ── MODULE REPORTS — ADMIN only ───────────────────────── */}
                {isAdmin && (
                    <>
                        <div className="gg-rp-section-label">Module Reports</div>
                        <div className="gg-rp-grid-3">

                            {/* Inventory — LIVE */}
                            <div className="gg-rp-report-card" style={{ animationDelay: '0.15s' }}>
                                <style>{`.gg-rp-report-card:nth-child(3)::before { background: #2d8fa5; }`}</style>
                                <div className="gg-rp-report-card-top">
                                    <div className="gg-rp-report-icon" style={{ background: 'rgba(45,143,165,0.1)', color: '#2d8fa5', border: '1px solid rgba(45,143,165,0.2)' }}><FaBoxOpen /></div>
                                    <span className="gg-rp-live-badge"><span className="gg-rp-live-dot" /> Live</span>
                                </div>
                                <div className="gg-rp-report-title">Inventory Assets</div>
                                <div className="gg-rp-report-desc">Exports all asset records including name, category, location, quantity and status. Live data from the SGEMS database.</div>
                                <div className="gg-rp-owner">
                                    {inventoryData.length} asset{inventoryData.length !== 1 ? 's' : ''} in database · Owner: Senithu
                                </div>
                                <button className="gg-rp-dl-btn" onClick={downloadInventoryReport}
                                        style={{ background: 'linear-gradient(135deg, #1e6a7a, #2d8fa5)', color: '#fff', boxShadow: '0 4px 14px rgba(45,143,165,0.3)' }}>
                                    <FaFileDownload /> Download Inventory Report
                                </button>
                            </div>

                            {/* Billing — pending */}
                            <div className="gg-rp-report-card pending" style={{ animationDelay: '0.2s' }}>
                                <style>{`.gg-rp-report-card:nth-child(4)::before { background: #3b7abf; }`}</style>
                                <div className="gg-rp-report-card-top">
                                    <div className="gg-rp-report-icon" style={{ background: 'rgba(59,122,191,0.1)', color: '#3b7abf', border: '1px solid rgba(59,122,191,0.2)' }}><FaFileInvoiceDollar /></div>
                                    <span className="gg-rp-badge" style={{ background: 'rgba(59,122,191,0.1)', color: '#3b7abf' }}>Billing</span>
                                </div>
                                <div className="gg-rp-report-title">Monthly Revenue</div>
                                <div className="gg-rp-owner">Owner: Muditha</div>
                                <button className="gg-rp-dl-btn" onClick={() => showPendingAlert('Muditha')}
                                        style={{ background: 'rgba(59,122,191,0.08)', color: '#3b7abf', border: '1px solid rgba(59,122,191,0.2)' }}>
                                    <FaFileDownload /> Download PDF
                                </button>
                            </div>

                            {/* Maintenance — pending */}
                            <div className="gg-rp-report-card pending" style={{ animationDelay: '0.25s' }}>
                                <style>{`.gg-rp-report-card:nth-child(5)::before { background: #b94040; }`}</style>
                                <div className="gg-rp-report-card-top">
                                    <div className="gg-rp-report-icon" style={{ background: 'rgba(185,64,64,0.1)', color: '#b94040', border: '1px solid rgba(185,64,64,0.2)' }}><FaTools /></div>
                                    <span className="gg-rp-badge" style={{ background: 'rgba(185,64,64,0.1)', color: '#b94040' }}>Maintenance</span>
                                </div>
                                <div className="gg-rp-report-title">Maintenance Logs</div>
                                <div className="gg-rp-owner">Owner: Sehath</div>
                                <button className="gg-rp-dl-btn" onClick={() => showPendingAlert('Sehath')}
                                        style={{ background: 'rgba(185,64,64,0.08)', color: '#b94040', border: '1px solid rgba(185,64,64,0.2)' }}>
                                    <FaFileDownload /> Download PDF
                                </button>
                            </div>

                            {/* Alerts Report */}
                            <div className="gg-rp-report-card" style={{ animationDelay: '0.2s' }}>
                                <style>{`.gg-rp-report-card:nth-child(4)::before { background: #ef4444; }`}</style>
                                <div className="gg-rp-report-card-top">
                                    <div className="gg-rp-report-icon" style={{ background: 'rgba(239,68,68,0.1)', color: '#ef4444', border: '1px solid rgba(239,68,68,0.2)' }}><FaExclamationTriangle /></div>
                                    <span className="gg-rp-live-badge"><span className="gg-rp-live-dot" style={{ background: '#ef4444' }} /> Live</span>
                                </div>
                                <div className="gg-rp-report-title">Alert History</div>
                                <div className="gg-rp-report-desc">Exports all resolved/deleted alerts with timestamps, severity, and system details. Useful for compliance and trend analysis.</div>
                                <div className="gg-rp-owner">Owner: Kavidu</div>
                                <button className="gg-rp-dl-btn" onClick={downloadAlertReport}
                                        style={{ background: 'linear-gradient(135deg, #b91c1c, #ef4444)', color: '#fff', boxShadow: '0 4px 14px rgba(239,68,68,0.3)' }}>
                                    <FaFileDownload /> Download Alert Report
                                </button>
                            </div>

                        </div>
                    </>
                )}
            </div>
        </>
    );
}

export default Reports;