import React, { useEffect, useState, useContext } from 'react';
import { AuthContext } from '../../context/AuthContext';
import {
    FaFileDownload, FaSolarPanel, FaFileInvoiceDollar,
    FaTools, FaBoxOpen, FaUsers, FaFilter, FaSync, FaCheckCircle
} from 'react-icons/fa';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { toast } from 'react-toastify';

function Reports() {
    const { user } = useContext(AuthContext);
    const [energyData, setEnergyData] = useState([]);
    const [userData, setUserData] = useState([]);

    // ✅ NEW: Filter states
    const [dateRange, setDateRange] = useState('7');
    const [reportType, setReportType] = useState('all');
    const [format, setFormat] = useState('pdf');
    const [customDateFrom, setCustomDateFrom] = useState('');
    const [customDateTo, setCustomDateTo] = useState('');
    const [generating, setGenerating] = useState(false);

    // 1. FETCH DATA ON LOAD
    useEffect(() => {
        fetchData();
    }, [user, dateRange]); // ✅ Re-fetch when date range changes

    const fetchData = () => {
        // A. Fetch Site Energy Data with date range
        const daysParam = dateRange === 'custom' ? 30 : dateRange; // Default to 30 for custom
        fetch(`http://localhost:8080/api/stats/chart?role=ADMIN&days=${daysParam}`)
            .then(res => res.json())
            .then(data => setEnergyData(data))
            .catch(err => console.error("Energy fetch failed", err));

        // B. Fetch User Data (ONLY if Admin)
        if (user && user.role === 'ADMIN') {
            fetch(`http://localhost:8080/api/users`)
                .then(res => res.json())
                .then(data => setUserData(data))
                .catch(err => console.error("User fetch failed", err));
        }
    };

    // ✅ NEW: Generate report based on filters
    const handleGenerateReport = async () => {
        setGenerating(true);

        try {
            // Determine which report to generate
            if (reportType === 'all' || reportType === 'users') {
                if (user && user.role === 'ADMIN') {
                    await downloadUserReport();
                }
            }

            if (reportType === 'all' || reportType === 'energy') {
                await downloadEnergyReport();
            }

            toast.success(`${reportType === 'all' ? 'All reports' : reportType.charAt(0).toUpperCase() + reportType.slice(1) + ' report'} generated successfully!`);
        } catch (error) {
            toast.error("Failed to generate report. Please try again.");
        } finally {
            setGenerating(false);
        }
    };

    // ✅ NEW: Reset filters
    const handleResetFilters = () => {
        setDateRange('7');
        setReportType('all');
        setFormat('pdf');
        setCustomDateFrom('');
        setCustomDateTo('');
        toast.info("Filters reset to default");
    };

    // --- REPORT 1: USER DIRECTORY (ADMIN ONLY) ---
    const downloadUserReport = () => {
        return new Promise((resolve, reject) => {
            try {
                const doc = new jsPDF();

                // Header
                doc.setFontSize(18);
                doc.setTextColor(40, 167, 69);
                doc.text("SGEMS - System Users Directory", 14, 20);

                // Metadata
                doc.setFontSize(10);
                doc.setTextColor(100);
                doc.text(`Generated By: ${user.fullName} (User Admin)`, 14, 28);
                doc.text(`Date: ${new Date().toLocaleDateString()}`, 14, 33);
                doc.text(`Total Active Users: ${userData.length}`, 14, 38);
                doc.text(`Date Range: Last ${dateRange} days`, 14, 43); // ✅ NEW

                // Table
                autoTable(doc, {
                    head: [["ID", "Full Name", "Email", "Role", "Status"]],
                    body: userData.map(u => [u.id, u.fullName, u.email, u.role, "Active"]),
                    startY: 50,
                    theme: 'grid',
                    headStyles: { fillColor: [40, 167, 69] }
                });

                doc.save(`SGEMS_User_Report_${new Date().toISOString().split('T')[0]}.pdf`);
                resolve();
            } catch (e) {
                reject(e);
            }
        });
    };

    // --- REPORT 2: SITE ENERGY REPORT (SITE ADMIN) ---
    const downloadEnergyReport = () => {
        return new Promise((resolve, reject) => {
            try {
                const doc = new jsPDF();

                doc.setFontSize(18);
                doc.setTextColor(255, 193, 7);
                doc.text("SGEMS - Site Energy Generation", 14, 20);

                doc.setFontSize(10);
                doc.setTextColor(100);
                doc.text(`Generated By: ${user.fullName} (Site Admin)`, 14, 28);
                doc.text(`Date: ${new Date().toLocaleDateString()}`, 14, 33);
                doc.text(`Date Range: Last ${dateRange} days`, 14, 38); // ✅ NEW
                doc.text(`Total Records: ${energyData.length}`, 14, 43); // ✅ NEW

                // ✅ Calculate totals
                const totalGenerated = energyData.reduce((sum, row) => sum + row.generated, 0);
                const totalConsumed = energyData.reduce((sum, row) => sum + row.consumed, 0);
                const totalSavings = totalGenerated * 0.15;

                doc.text(`Total Generated: ${totalGenerated.toFixed(2)} kWh`, 14, 48);
                doc.text(`Total Consumed: ${totalConsumed.toFixed(2)} kWh`, 14, 53);
                doc.text(`Total Savings: $${totalSavings.toFixed(2)}`, 14, 58);

                autoTable(doc, {
                    head: [["Day", "Generated (kWh)", "Consumed (kWh)", "Savings ($)"]],
                    body: energyData.map(row => [
                        row.day,
                        row.generated.toFixed(2),
                        row.consumed.toFixed(2),
                        `$${(row.generated * 0.15).toFixed(2)}`
                    ]),
                    startY: 65,
                    headStyles: { fillColor: [255, 193, 7], textColor: [0, 0, 0] }
                });

                doc.save(`SGEMS_Energy_Report_${new Date().toISOString().split('T')[0]}.pdf`);
                resolve();
            } catch (e) {
                reject(e);
            }
        });
    };

    // --- TEAMMATE PLACEHOLDER ALERT ---
    const showPendingAlert = (name) => {
        toast.info(`🚧 Waiting for ${name} to implement their API endpoint!`);
    };

    return (
        <div className="container-fluid">
            <h2 className="mb-2">System Reports Hub</h2>
            <p className="text-muted mb-4">Generate legal and operational reports for all system modules.</p>

            {/* ✅ NEW: REPORT FILTERS SECTION */}
            <div className="card shadow-sm mb-4">
                <div className="card-header bg-primary text-white">
                    <FaFilter className="me-2" />
                    Report Filters & Customization
                </div>
                <div className="card-body">
                    <div className="row g-3">
                        {/* Date Range Selector */}
                        <div className="col-md-4">
                            <label className="form-label fw-bold">Date Range</label>
                            <select
                                className="form-select"
                                value={dateRange}
                                onChange={(e) => setDateRange(e.target.value)}
                            >
                                <option value="7">Last 7 Days</option>
                                <option value="14">Last 14 Days</option>
                                <option value="30">Last 30 Days</option>
                                <option value="90">Last 90 Days</option>
                                <option value="custom">Custom Range</option>
                            </select>
                        </div>

                        {/* Report Type Selector */}
                        <div className="col-md-4">
                            <label className="form-label fw-bold">Report Type</label>
                            <select
                                className="form-select"
                                value={reportType}
                                onChange={(e) => setReportType(e.target.value)}
                            >
                                <option value="all">All Reports</option>
                                <option value="energy">Energy Generation</option>
                                {user && user.role === 'ADMIN' && (
                                    <option value="users">User Directory</option>
                                )}
                            </select>
                        </div>

                        {/* Format Selector */}
                        <div className="col-md-4">
                            <label className="form-label fw-bold">Export Format</label>
                            <select
                                className="form-select"
                                value={format}
                                onChange={(e) => setFormat(e.target.value)}
                            >
                                <option value="pdf">PDF Document</option>
                                <option value="excel">Excel Spreadsheet (Coming Soon)</option>
                                <option value="csv">CSV File (Coming Soon)</option>
                            </select>
                        </div>

                        {/* Custom Date Range */}
                        {dateRange === 'custom' && (
                            <>
                                <div className="col-md-6">
                                    <label className="form-label fw-bold">From Date</label>
                                    <input
                                        type="date"
                                        className="form-control"
                                        value={customDateFrom}
                                        onChange={(e) => setCustomDateFrom(e.target.value)}
                                    />
                                </div>
                                <div className="col-md-6">
                                    <label className="form-label fw-bold">To Date</label>
                                    <input
                                        type="date"
                                        className="form-control"
                                        value={customDateTo}
                                        onChange={(e) => setCustomDateTo(e.target.value)}
                                        max={new Date().toISOString().split('T')[0]}
                                    />
                                </div>
                            </>
                        )}

                        {/* Action Buttons */}
                        <div className="col-12">
                            <div className="d-flex gap-2">
                                <button
                                    className="btn btn-success"
                                    onClick={handleGenerateReport}
                                    disabled={generating}
                                >
                                    {generating ? (
                                        <>
                                            <span className="spinner-border spinner-border-sm me-2"></span>
                                            Generating...
                                        </>
                                    ) : (
                                        <>
                                            <FaFileDownload className="me-2" />
                                            Generate Report
                                        </>
                                    )}
                                </button>
                                <button
                                    className="btn btn-outline-secondary"
                                    onClick={handleResetFilters}
                                >
                                    <FaSync className="me-2" />
                                    Reset Filters
                                </button>
                            </div>
                        </div>
                    </div>

                    {/* Filter Summary */}
                    <div className="alert alert-info mt-3 mb-0">
                        <small>
                            <FaCheckCircle className="me-2" />
                            <strong>Current Selection:</strong> {reportType === 'all' ? 'All Reports' : reportType.charAt(0).toUpperCase() + reportType.slice(1)} report
                            {' '}- {dateRange === 'custom' ? `${customDateFrom} to ${customDateTo}` : `Last ${dateRange} days`}
                            {' '}- Format: {format.toUpperCase()}
                        </small>
                    </div>
                </div>
            </div>

            {/* EXISTING REPORT CARDS */}
            <div className="row g-4">

                {/* --- ADMINISTRATIVE SECTION --- */}
                <div className="col-12">
                    <h5 className="text-success border-bottom pb-2">Your Administrative Reports</h5>
                </div>

                {/* 1. USER DIRECTORY (SECURE: HIDDEN FOR NON-ADMINS) */}
                {user && user.role === 'ADMIN' && (
                    <div className="col-md-6">
                        <div className="card h-100 shadow-sm border-start border-success border-4">
                            <div className="card-body">
                                <div className="d-flex justify-content-between align-items-center mb-3">
                                    <h5 className="card-title mb-0"><FaUsers className="me-2"/>User Directory</h5>
                                    <span className="badge bg-success">User Admin Module</span>
                                </div>
                                <p className="text-muted small">
                                    Exports a list of all registered users, their roles, and account status.
                                    Required for security auditing.
                                </p>
                                <button onClick={downloadUserReport} className="btn btn-success w-100">
                                    <FaFileDownload className="me-2"/> Download User Report
                                </button>
                            </div>
                        </div>
                    </div>
                )}

                {/* 2. SITE GENERATION (VISIBLE TO SITE ADMIN/USER) */}
                <div className="col-md-6">
                    <div className="card h-100 shadow-sm border-start border-warning border-4">
                        <div className="card-body">
                            <div className="d-flex justify-content-between align-items-center mb-3">
                                <h5 className="card-title mb-0"><FaSolarPanel className="me-2"/>Site Generation</h5>
                                <span className="badge bg-warning text-dark">Site Admin Module</span>
                            </div>
                            <p className="text-muted small">
                                Exports daily energy production, consumption, and savings analysis from Solarman API.
                            </p>
                            <button onClick={downloadEnergyReport} className="btn btn-warning w-100">
                                <FaFileDownload className="me-2"/> Download Energy Report
                            </button>
                        </div>
                    </div>
                </div>

                {/* --- TEAMMATES SECTION --- */}
                <div className="col-12 mt-4">
                    <h5 className="text-muted border-bottom pb-2">Other Modules (Pending Integration)</h5>
                </div>

                {/* 3. Muditha (Billing) */}
                <div className="col-md-4">
                    <div className="card h-100 border-start border-primary border-4 opacity-75">
                        <div className="card-body">
                            <h6><FaFileInvoiceDollar className="me-2 text-primary"/>Monthly Revenue</h6>
                            <p className="small text-muted">Owner: Muditha</p>
                            <button onClick={() => showPendingAlert('Muditha')} className="btn btn-outline-primary btn-sm w-100">
                                <FaFileDownload className="me-2"/> Download PDF
                            </button>
                        </div>
                    </div>
                </div>

                {/* 4. Sehath (Maintenance) */}
                <div className="col-md-4">
                    <div className="card h-100 border-start border-danger border-4 opacity-75">
                        <div className="card-body">
                            <h6><FaTools className="me-2 text-danger"/>Maintenance Logs</h6>
                            <p className="small text-muted">Owner: Sehath</p>
                            <button onClick={() => showPendingAlert('Sehath')} className="btn btn-outline-danger btn-sm w-100">
                                <FaFileDownload className="me-2"/> Download PDF
                            </button>
                        </div>
                    </div>
                </div>

                {/* 5. Senithu (Inventory) */}
                <div className="col-md-4">
                    <div className="card h-100 border-start border-info border-4 opacity-75">
                        <div className="card-body">
                            <h6><FaBoxOpen className="me-2 text-info"/>Inventory Assets</h6>
                            <p className="small text-muted">Owner: Senithu</p>
                            <button onClick={() => showPendingAlert('Senithu')} className="btn btn-outline-info btn-sm w-100">
                                <FaFileDownload className="me-2"/> Download PDF
                            </button>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    );
}

export default Reports;