import React, { useEffect, useState, useContext } from 'react';
import { AuthContext } from '../../context/AuthContext';
import {
    FaFileDownload, FaSolarPanel, FaFileInvoiceDollar,
    FaTools, FaBoxOpen, FaUsers
} from 'react-icons/fa';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { toast } from 'react-toastify'; // <--- PROFESSIONAL NOTIFICATIONS

function Reports() {
    const { user } = useContext(AuthContext);
    const [energyData, setEnergyData] = useState([]);
    const [userData, setUserData] = useState([]);

    // 1. FETCH DATA ON LOAD
    useEffect(() => {
        // A. Fetch Site Energy Data (For Site Admin Report)
        fetch(`http://localhost:8080/api/stats/chart?role=ADMIN`)
            .then(res => res.json())
            .then(data => setEnergyData(data))
            .catch(err => console.error("Energy fetch failed", err));

        // B. Fetch User Data (ONLY if Admin)
        if (user && user.role === 'ADMIN') {
            fetch(`http://localhost:8080/api/users`)
                .then(res => res.json())
                .then(data => setUserData(data))
                .catch(err => console.error("User fetch failed", err));
        }
    }, [user]);

    // --- REPORT 1: USER DIRECTORY (ADMIN ONLY) ---
    const downloadUserReport = () => {
        try {
            const doc = new jsPDF();

            // Header
            doc.setFontSize(18);
            doc.setTextColor(40, 167, 69); // GreenGrid Green
            doc.text("SGEMS - System Users Directory", 14, 20);

            // Metadata
            doc.setFontSize(10);
            doc.setTextColor(100);
            doc.text(`Generated By: ${user.fullName} (User Admin)`, 14, 28);
            doc.text(`Date: ${new Date().toLocaleDateString()}`, 14, 33);
            doc.text(`Total Active Users: ${userData.length}`, 14, 38);

            // Table
            autoTable(doc, {
                head: [["ID", "Full Name", "Email", "Role", "Status"]],
                body: userData.map(u => [u.id, u.fullName, u.email, u.role, "Active"]),
                startY: 45,
                theme: 'grid',
                headStyles: { fillColor: [40, 167, 69] }
            });

            doc.save("SGEMS_User_Report.pdf");
            toast.success("User Report Downloaded Successfully!");
        } catch (e) {
            toast.error("Failed to generate User Report.");
        }
    };

    // --- REPORT 2: SITE ENERGY REPORT (SITE ADMIN) ---
    const downloadEnergyReport = () => {
        try {
            const doc = new jsPDF();

            doc.setFontSize(18);
            doc.setTextColor(255, 193, 7); // Warning/Solar Yellow
            doc.text("SGEMS - Site Energy Generation", 14, 20);

            doc.setFontSize(10);
            doc.setTextColor(100);
            doc.text(`Generated By: ${user.fullName} (Site Admin)`, 14, 28);

            autoTable(doc, {
                head: [["Day", "Generated (kWh)", "Consumed (kWh)", "Savings ($)"]],
                body: energyData.map(row => [
                    row.day,
                    row.generated.toFixed(2),
                    row.consumed.toFixed(2),
                    `$${(row.generated * 0.15).toFixed(2)}`
                ]),
                startY: 35,
                headStyles: { fillColor: [255, 193, 7], textColor: [0,0,0] }
            });

            doc.save("SGEMS_Energy_Report.pdf");
            toast.success("Energy Report Downloaded Successfully!");
        } catch (e) {
            toast.error("Failed to generate Energy Report.");
        }
    };

    // --- TEAMMATE PLACEHOLDER ALERT ---
    const showPendingAlert = (name) => {
        // Uses the professional Toast instead of alert()
        toast.info(`🚧 Waiting for ${name} to implement their API endpoint!`);
    };

    return (
        <div className="container-fluid">
            <h2 className="mb-2">System Reports Hub</h2>
            <p className="text-muted mb-4">Generate legal and operational reports for all system modules.</p>

            <div className="row g-4">

                {/* --- ADMINISTRATIVE SECTION --- */}
                <div className="col-12">
                    <h5 className="text-success border-bottom pb-2">Your Administrative Reports</h5>
                </div>

                {/* 1. USER DIRECTORY (SECURE: HIDDEN FOR NON-ADMINS) */}
                {user && user.role === 'ADMIN' && (
                    <div className="col-md-6">
                        <div className="card h-100 shadow-sm border-start border-success border-4">
                            <div className="card-body">
                                <div className="d-flex justify-content-between align-items-center mb-3">
                                    <h5 className="card-title mb-0"><FaUsers className="me-2"/>User Directory</h5>
                                    <span className="badge bg-success">User Admin Module</span>
                                </div>
                                <p className="text-muted small">
                                    Exports a list of all registered users, their roles, and account status.
                                    Required for security auditing.
                                </p>
                                <button onClick={downloadUserReport} className="btn btn-success w-100">
                                    <FaFileDownload className="me-2"/> Download User Report
                                </button>
                            </div>
                        </div>
                    </div>
                )}

                {/* 2. SITE GENERATION (VISIBLE TO SITE ADMIN/USER) */}
                <div className="col-md-6">
                    <div className="card h-100 shadow-sm border-start border-warning border-4">
                        <div className="card-body">
                            <div className="d-flex justify-content-between align-items-center mb-3">
                                <h5 className="card-title mb-0"><FaSolarPanel className="me-2"/>Site Generation</h5>
                                <span className="badge bg-warning text-dark">Site Admin Module</span>
                            </div>
                            <p className="text-muted small">
                                Exports daily energy production, consumption, and savings analysis from Solarman API.
                            </p>
                            <button onClick={downloadEnergyReport} className="btn btn-warning w-100">
                                <FaFileDownload className="me-2"/> Download Energy Report
                            </button>
                        </div>
                    </div>
                </div>

                {/* --- TEAMMATES SECTION --- */}
                <div className="col-12 mt-4">
                    <h5 className="text-muted border-bottom pb-2">Team Modules (Pending Integration)</h5>
                </div>

                {/* 3. Muditha (Billing) */}
                <div className="col-md-4">
                    <div className="card h-100 border-start border-primary border-4 opacity-75">
                        <div className="card-body">
                            <h6><FaFileInvoiceDollar className="me-2 text-primary"/>Monthly Revenue</h6>
                            <p className="small text-muted">Owner: Muditha</p>
                            <button onClick={() => showPendingAlert('Muditha')} className="btn btn-outline-primary btn-sm w-100">
                                <FaFileDownload className="me-2"/> Download PDF
                            </button>
                        </div>
                    </div>
                </div>

                {/* 4. Sehath (Maintenance) */}
                <div className="col-md-4">
                    <div className="card h-100 border-start border-danger border-4 opacity-75">
                        <div className="card-body">
                            <h6><FaTools className="me-2 text-danger"/>Maintenance Logs</h6>
                            <p className="small text-muted">Owner: Sehath</p>
                            <button onClick={() => showPendingAlert('Sehath')} className="btn btn-outline-danger btn-sm w-100">
                                <FaFileDownload className="me-2"/> Download PDF
                            </button>
                        </div>
                    </div>
                </div>

                {/* 5. Senithu (Inventory) */}
                <div className="col-md-4">
                    <div className="card h-100 border-start border-info border-4 opacity-75">
                        <div className="card-body">
                            <h6><FaBoxOpen className="me-2 text-info"/>Inventory Assets</h6>
                            <p className="small text-muted">Owner: Senithu</p>
                            <button onClick={() => showPendingAlert('Senithu')} className="btn btn-outline-info btn-sm w-100">
                                <FaFileDownload className="me-2"/> Download PDF
                            </button>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    );
}

export default Reports;